language: c
arch:
  - amd64
  - ppc64le
compiler:
  - gcc

install: 
  - sudo apt-get update || true
  - sudo apt-get install build-essential
  - sudo apt-get install libpcap-dev libpcre2-dev autoconf automake autogen

script:
  - ./build.sh
  - ./configure
  - make
  - ./src/sipgrep -h

notifications:
  slack: qxip:WuEGMSIAa8KEX6iL2zN2bZbv
